#!/usr/bin/env python

import argparse
import docker
import time
import sys
import itertools
import traceback
import signal
import os
from jinja2 import Template, Environment, FileSystemLoader, select_autoescape, TemplateNotFound

jinjaenv = Environment(
    loader=FileSystemLoader(["/templates", "templates"]),
    autoescape=select_autoescape(['conf'])
)

def hostlabel(c):
    if 'proxy.host' in c.labels:
        return c.labels['proxy.host']
    return None

def regenerate(args, client):
    print "Regenerating"

    def key(c):
        if 'proxy.host' in c.labels:
            h = c.labels['proxy.host']
        else:
            h = None

        return h

    

    # Remove all existing files
    map(os.remove, ["{}/{}".format(args.dir, x) for x in os.listdir(args.dir) if x.endswith(".conf")])

    # now generate more conf files
    for label, containers in itertools.groupby(sorted(client.containers.list(), key=key), key):
        generate(args, label, map(lambda x: client.api.inspect_container(x.id), containers))

    notify(args, client.containers.list())


def notify(args, containers):
    def notify(c):
        print "Notifying {} with SIGHUP".format(c.name)
        c.kill(signal=signal.SIGHUP)

    map(notify, [c for c in containers if "proxy.notify" in c.labels])


def generate(args, label, containers):
    if label is None:
        return

    hostname = label
    fromport = 80

    try:
        t = jinjaenv.get_template("{}.conf".format(hostname))
    except TemplateNotFound:
        t = jinjaenv.get_template("default.conf")

    c = list(containers)

    print "Containers for {}: {}".format(label, ", ".join([x['Name'] for x in containers]))

    content = t.render(hostname=hostname, fromport = fromport, containers=c, c1=c[0])

    if content != "":
        filename = "{}/{}_{}.conf".format(args.dir, hostname, fromport)
        print "Printing to %s" % filename
        with open(filename, "w") as f:
            f.write(content)


def main():
    parser = argparse.ArgumentParser(description="Generate conf files from docker")

    parser.add_argument("-append-instance-id", help="append instance ID to directory", action='store_true')
    parser.add_argument("-dir", help="directory into which to generate files", default="/etc/nginx/conf.d")
    parser.add_argument("-verbose", help="Verbose output", action='store_true')
    args = parser.parse_args()

    while True:
        try:
            client = docker.from_env()
            regenerate(args, client)

            for e in client.api.events(decode=True):
                if e['Action'] in ['start', 'die']:
                    regenerate(args, client)
        except KeyboardInterrupt:
            sys.exit(1)
        except:
            traceback.print_exc()
            time.sleep(5)

if __name__ == "__main__":
    main()


